# Scheduled build

trigger: none

schedules:
  - cron: "20 2 * * *"
    displayName: Scheduled build
    branches:
      include:
        - master
    always: true

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  - name: dockerRegistryServiceConnection
    value: '206f95a6-9c4e-4868-9f2e-588ae6d5050f'
  - name: containerRegistry
    value: 'bitsregistry.azurecr.io'
  - name: debug
    value: true
  - name: imageRepository
    value: 'tam-file-event-handler-api'
  - name: dockerfilePath
    value: '**/Dockerfile'
  - name: tag
    value: '$(Build.BuildNumber)'

  # Key vault
  - group: variables-tam-aks-test

  
  # Agent VM image name
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
    - task: replacetokens@3
      inputs:
        targetFiles: 'manifests/*.yml'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - upload: manifests
      artifact: manifests
    - task: WhiteSource@21
      displayName: Mend
